---
# Mongo credentials for MAS
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "mongodb-mongoce-admin"
  namespace: "mas-{{mas_instance_id}}-core"
stringData:
  username: admin
  password: "{{ mongodb_admin_password }}"
---
# Mongo configuration for MAS
apiVersion: config.mas.ibm.com/v1
kind: MongoCfg
metadata:
  name: "{{mas_instance_id}}-mongo-system"
  namespace: "mas-{{mas_instance_id}}-core"
  labels:
    mas.ibm.com/configScope: system
    mas.ibm.com/instanceId: "{{mas_instance_id}}"
spec:
  displayName: "MongoDb 4.2.6 Community Edition in '{{ mongodb_namespace }}' namespace"
  type: external
  config:
    configDb: admin
    authMechanism: DEFAULT
    credentials:
      secretName: mongodb-mongoce-admin
    hosts:
      {{ mongo_hosts | indent(6) }}
  certificates:
    - alias: ca
      crt: |
        {{ mongodb_ca_pem | indent(8) }}
