---
# Configure COS bucket for Manage attachments
# -----------------------------------------------------------------------------
- name: "Configure COS bucket for Manage attachments"
  include_role:
    name: ibm.mas_devops.cos_bucket
