---
# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "{{ item }} : Fail if required properties are not provided"
  assert:
    that:
      - openshift_release_version is defined and openshift_release_version != ""
      - redhat_pullsecret is defined and redhat_pullsecret != ""
      - mirror_working_dir is defined and mirror_working_dir != ""
    fail_msg: "One or more required properties are missing"


# 2. Perform Mirroring
# -----------------------------------------------------------------------------
- name: "{{ item }} : Generate Operator Index Manifest (to filesystem)"
  shell: >
    oc adm catalog mirror registry.redhat.io/redhat/{{ item }}:v{{ openshift_operators_version }} file://redhat/{{ item }} \
      -a {{ redhat_pullsecret }} \
      --dir={{ mirror_working_dir }} \
      --index-filter-by-os='linux/amd64' \
      --manifests-only
      --to-manifests={{ mirror_working_dir }}/manifests/to-filesystem
  register: mirror_result

- name: "{{ item }} : Mirror Operator Index (to filesystem)"
  shell: >
    oc image mirror \
      -a {{ redhat_pullsecret }} \
      --dir={{ mirror_working_dir }} \
      --keep-manifest-list=true \
      -f {{ mirror_working_dir }}/manifests/to-filesystem/mapping.txt
  register: mirror_result

- name: "{{ item }} : Debug Mirror"
  debug:
    msg: "{{ mirror_result.stdout_lines }}"
