---
# 1. Install Service Binding Operator
# -----------------------------------------------------------------------------
# Only supported version of MAS that requires SBO is 8.7.x, all other releases require no action
- name: "Launch SBO install"
  when: mas_channel == "8.7.x"
  include_tasks: "tasks/install/stable.yml"
