---
# Application specific variables for Health
mas_app_ws_fqn: healthworkspaces.apps.mas.ibm.com
mas_app_ws_apiversion: apps.mas.ibm.com/v1
mas_app_ws_kind: HealthWorkspace
mas_app_cfg_retries: 50
mas_app_cfg_delay: 480

mas_app_settings_aio_flag: "{{ lookup('env', 'MAS_APP_SETTINGS_AIO_FLAG') | default('true', true)}}"
mas_app_settings_db2_schema: "{{ lookup('env', 'MAS_APP_SETTINGS_DB2_SCHEMA') | default('maximo', true)}}"
mas_app_settings_demodata: "{{ lookup('env', 'MAS_APP_SETTINGS_DEMODATA') | default('false', true) }}"

server_bundles_jms_add_server_config_secret_name: "{{ mas_workspace_id }}-manage-jms-additional-server-config"
server_bundles_add_server_config_secret_name: "{{ mas_workspace_id }}-manage-additional-server-config"
mas_app_settings_persistent_volumes_flag: "{{ lookup('env', 'MAS_APP_SETTINGS_PERSISTENT_VOLUMES_FLAG') | default('false', true) }}"
mas_app_settings_server_bundles_size: "{{ lookup('env', 'MAS_APP_SETTINGS_SERVER_BUNDLES_SIZE') | default('dev', true)  }}"
mas_app_settings_server_bundles:
  dev:
    serverBundles:
      - bundleType: all
        isDefault: true
        isMobileTarget: true
        isUserSyncTarget: true
        name: all
        replica: 1
        routeSubDomain: all
  small:
    serverBundles:
      - bundleType: ui
        isDefault: true
        isMobileTarget: true
        isUserSyncTarget: false
        name: ui
        replica: 1
        routeSubDomain: ui
      - bundleType: mea
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: true
        name: mea
        replica: 1
        routeSubDomain: mea
      - bundleType: report
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: false
        name: report
        replica: 1
        routeSubDomain: report
      - bundleType: cron
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: false
        name: cron
        replica: 1
        routeSubDomain: cron
  jms:
    serverBundles:
      - additionalServerConfig:
          secretName: "{{ server_bundles_add_server_config_secret_name }}"
        bundleType: ui
        isDefault: true
        isMobileTarget: true
        isUserSyncTarget: false
        name: ui
        replica: 1
        routeSubDomain: ui
      - additionalServerConfig:
          secretName: "{{ server_bundles_add_server_config_secret_name }}"
        bundleType: mea
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: true
        name: mea
        replica: 1
        routeSubDomain: mea
      - additionalServerConfig:
          secretName: "{{ server_bundles_add_server_config_secret_name }}"
        bundleType: report
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: false
        name: report
        replica: 1
        routeSubDomain: report
      - additionalServerConfig:
          secretName: "{{ server_bundles_add_server_config_secret_name }}"
        bundleType: cron
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: false
        name: cron
        replica: 1
        routeSubDomain: cron
      - additionalServerConfig:
          secretName: "{{ server_bundles_jms_add_server_config_secret_name }}"
        bundleType: standalonejms
        isDefault: false
        isMobileTarget: false
        isUserSyncTarget: false
        name: jms
        replica: 1
        routeSubDomain: jms
