---
mas_app_ws_fqn: predictworkspaces.apps.mas.ibm.com
mas_app_ws_apiversion: apps.mas.ibm.com/v1
mas_app_ws_kind: PredictWorkspace

mas_app_cfg_delay: 120
mas_app_cfg_retries: 30

mas_app_settings_wml_instance_id: "{{ lookup('env', 'WML_INSTANCE_ID') | default('openshift', true) }}"
mas_app_settings_wml_url: "{{ lookup('env', 'WML_URL') | default('https://internal-nginx-svc.ibm-cpd.svc:12443', true) }}"
mas_app_settings_wml_version: "{{ lookup('env', 'WML_VERSION') }}"
mas_app_settings_predict_deployment_size: "{{ lookup('env', 'PREDICT_DEPLOYMENT_SIZE') | default('small', true) }}"

# CPD version is required by predict to identify what version of WML must be used to activate predict
# if this information is used by more than predict, it should be moved to defaults/main.yml of the role
cpd_product_version: "{{ lookup('env', 'CPD_PRODUCT_VERSION') }}"

cpd_wml_dictionary:
  "4.5": "4.5"
  "4.0": "4.0"
