---

- name: Load CASE bundle versions
  include_vars:
    file: "{{ role_path }}/../../common_vars/casebundles/{{ mas_catalog_version }}.yml"

# We only support Core + 3 applications with disconnected installs today:
# - Core
# - IoT
# - Manage
# - Optimizer
#
# When new apps are supported they will need to be added here too (unless they are
# upgraded to v2 airgap support which does not need the additional config map to be
# installed).


# 1. Updates for Core
# -----------------------------------------------------------------------------
- kubernetes.core.k8s_info:
    api_version: core.mas.ibm.com/v1
    kind: Suite
  register: suites

- name: "Update ibm-mas Image Digest Map (8.8.x)"
  when: "'8.8.x' is in mas_core_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ suites.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas
    case_version: "{{ mas_core_version['8.8.x'] }}"

- name: "Update ibm-mas Image Digest Map (8.9.x)"
  when: "'8.9.x' is in mas_core_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ suites.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas
    case_version: "{{ mas_core_version['8.9.x'] }}"


# 2. Updates for IoT
# -----------------------------------------------------------------------------
- kubernetes.core.k8s_info:
    api_version: iot.ibm.com/v1
    kind: IoT
  register: iot_apps

- name: "Update ibm-mas-iot Image Digest Map (8.8.x)"
  when: "'8.8.x' is in mas_iot_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ iot_apps.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas-iot
    case_version: "{{ mas_iot_version['8.8.x'] }}"

- name: "Update ibm-mas-iot Image Digest Map (8.9.x)"
  when: "'8.9.x' is in mas_iot_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ iot_apps.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas-iot
    case_version: "{{ mas_iot_version['8.9.x'] }}"


# 3. Updates for Manage
# -----------------------------------------------------------------------------
- kubernetes.core.k8s_info:
    api_version: apps.mas.ibm.com/v1
    kind: ManageApp
  register: manage_apps

- name: "Update ibm-mas-manage Image Digest Map (8.8.x)"
  when: "'8.8.x' is in mas_manage_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ manage_apps.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas-manage
    case_version: "{{ mas_manage_version['8.8.x'] }}"

- name: "Update ibm-mas-manage Image Digest Map (8.9.x)"
  when: "'8.9.x' is in mas_manage_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ manage_apps.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas-manage
    case_version: "{{ mas_manage_version['8.9.x'] }}"


# 3. Updates for Optimizer
# -----------------------------------------------------------------------------
- kubernetes.core.k8s_info:
    api_version: apps.mas.ibm.com/v1
    kind: optimizerApp
  register: optimizer_apps

- name: "Update ibm-mas-optimizer Image Digest Map (8.8.x)"
  when: "'8.8.x' is in mas_optimizer_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ optimizer_apps.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas-optimizer
    case_version: "{{ mas_optimizer_version['8.8.x'] }}"

- name: "Update ibm-mas-optimizer Image Digest Map (8.9.x)"
  when: "'8.9.x' is in mas_optimizer_version"
  include_role:
    name: ibm.mas_devops.suite_install_digest_cm
  with_items: "{{ optimizer_apps.resources }}"
  vars:
    digest_image_map_namespace: "{{ item.metadata.namespace }}"
    case_name: ibm-mas-optimizer
    case_version: "{{ mas_optimizer_version['8.9.x'] }}"
