---

# Provide intelligent storage class selection to minimize required user knowledge

# 1. Lookup storage class availabiity
# -----------------------------------------------------------------------------
- name: "determine-storage-classes : Lookup storage classes"
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
  register: lookup_storageclasses

- name: "Debug available storage classes"
  debug:
    msg: "{{ lookup_storageclasses | ibm.mas_devops.getResourceNames }}"

# 2. Set FPL Storage (Required)
# -----------------------------------------------------------------------------
- name: "determine-storage-classes : Default IoT FPL PVC Storage if not set by user"
  when:
    - mas_app_settings_iot_fpl_pvc_storage_class is not defined or mas_app_settings_iot_fpl_pvc_storage_class == ""
    - mas_app_settings_iot_deployment_size != "dev"

  vars:
    # ROKS, OCS, AWS, Azure
    supported_storage_classes: [ibmc-block-gold, ocs-storagecluster-ceph-rbd, gp2, managed-premium]
  set_fact:
    mas_app_settings_iot_fpl_pvc_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(supported_storage_classes) }}"

# 3. Debug storage class configuration
# -----------------------------------------------------------------------------
- name: "determine-storage-classes : Debug Manage PVC storage class configuration"
  debug:
    msg:
      - "IoT Deployment Size .......... {{ mas_app_settings_iot_deployment_size }}"
      - "IoT FPL PVC Storage Class .......... {{ mas_app_settings_iot_fpl_pvc_storage_class }}"
      - "IoT FPL PVC Router Size ................... {{ mas_app_settings_iot_fpl_router_pvc_size }} "
      - "IoT FPL PVC Executor Size ................... {{ mas_app_settings_iot_fpl_executor_pvc_size }} "
