---
# 2. We need to perform a merge to add the data to the configmap
- name: "Get existing image map data"
  set_fact:
    existing_digest_image_map_data: "{{ existing_digest_cm.resources[0].data['image-map.yaml'] }}"

- name: "Install the updated digest config map"
  kubernetes.core.k8s:
    template: 'templates/configmap.yml.j2'
