---
# Default application spec for Predict
mas_app_ws_spec:
  bindings:
    jdbc: system
    watsonstudio: system
  settings:
    wml:
      instance_id: "{{ mas_app_settings_wml_instance_id }}"
      url: "{{ mas_app_settings_wml_url }}"
      version: "{{ mas_app_settings_wml_version }}"
    deployment:
      size: "{{ mas_app_settings_predict_deployment_size}}"
