---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - openshift_release_version is defined and openshift_release_version != ""
      - mirror_mode is defined and mirror_mode != ""
    fail_msg: "One or more required properties are missing"


# 2. Check for required software
# -----------------------------------------------------------------------------
- name: "Test if oc is installed"
  shell: oc help
  register: _oc_help
  ignore_errors: true

- name: "Fail if oc is not installed"
  assert:
    that: ( _oc_help['rc'] == 0 )
    fail_msg: "oc tool must be installed."


# 3. Debug
# -----------------------------------------------------------------------------
- name: "Airgap setup configuration"
  debug:
    msg:
      - "OpenShift Release Version .............. {{ openshift_release_version }}"
      - "Mirror Mode ............................ {{ mirror_mode }}"


# 4. Mirror Release To Disk
# -----------------------------------------------------------------------------
- name: Run Mirroring
  include_tasks: "actions/{{ mirror_mode }}.yml"
