---
# Create authentication credentials for the instance
# ---------------------------------------------------------------------------------------------------------------------
- name: "Create IBM COS service credentials with role {{ ibmcos_resource_key_iam_role }}"
  ibm.cloudcollection.ibm_resource_key:
    name: "{{ ibmcos_service_credentials_name }}"
    role: "{{ ibmcos_resource_key_iam_role }}"
    resource_instance_id: "{{ ibmcos_resource_id }}"
    ibmcloud_api_key: "{{ ibmcloud_apikey  }}"
    parameters: {'HMAC': true }

- name: "Retrieve IBM COS service credentials {{ ibmcos_service_credentials_name }}"
  ibm.cloudcollection.ibm_resource_key_info:
    name: "{{ ibmcos_service_credentials_name }}"
    resource_instance_id: "{{ ibmcos_resource_id }}"
    ibmcloud_api_key: "{{ ibmcloud_apikey  }}"
  register: cos_key_info

- name: "Set access key id & secret access key variables"
  set_fact:
    ibmcos_url: "{{ ibmcos_url }}"
    ibmcos_bucket_name: "{{ ibmcos_bucket_name }}"
    ibmcos_access_key_id: "{{ cos_key_info.resource.credentials['cos_hmac_keys.access_key_id'] }}"
    ibmcos_secret_access_key: "{{ cos_key_info.resource.credentials['cos_hmac_keys.secret_access_key'] }}"
