---
# Default application spec for IoT
mas_app_spec:
  bindings:
    jdbc: system
    mongo: system
    kafka: system
  components: {}
  settings:
    deployment:
      size: "{{ mas_app_settings_iot_deployment_size }}"
    fpl:
      functionsexecutor:
        storage:
          class: "{{ mas_app_settings_iot_fpl_pvc_storage_class }}"
          size: "{{ mas_app_settings_iot_fpl_executor_pvc_size }}"
      pipelinerouter:
        storage:
          class: "{{ mas_app_settings_iot_fpl_pvc_storage_class }}"
          size: "{{ mas_app_settings_iot_fpl_router_pvc_size }}"
