---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - openshift_release_version is defined and openshift_release_version != ""
      - mirror_mode is defined and mirror_mode != ""
    fail_msg: "One or more required properties are missing"


# 2. Check for required software
# -----------------------------------------------------------------------------
- name: "Test if oc is installed"
  shell: oc help
  register: _oc_help
  ignore_errors: true

- name: "Fail if oc is not installed"
  assert:
    that: ( _oc_help['rc'] == 0 )
    fail_msg: "oc tool must be installed."


# 3. Debug
# -----------------------------------------------------------------------------
- name: "Airgap setup configuration"
  debug:
    msg:
      - "OpenShift Operators Version ............ {{ openshift_operators_version }}"
      - "Mirror Mode ............................ {{ mirror_mode }}"


# 4. Mirror Release
# -----------------------------------------------------------------------------
- name: Run Mirroring
  include_tasks: "actions/{{ mirror_mode }}.yml"
  with_items:
    - redhat-operator-index    # Fails ... see support ticket https://access.redhat.com/support/cases/#/case/03362302
    - community-operator-index # Fails ... docker.io pull rate limits make this non-viable today
    - certified-operator-index # Fails ... error: unable to retrieve source image quay.io/kove/kove-xmem manifest sha256:4db798be1ec40d38b84a12d6fce97bd72e3a51d2811725f1023caef33e3dfce7: unauthorized: access to the requested resource is not authorized
    - redhat-marketplace-index # Fails ... error: unable to retrieve source image registry.connect.redhat.com/zabbix/zabbix-agent-50 manifest sha256:229562a27ed45319ef17397fe81cac81129c84eccd2c14f6085531a86ef9b87d: name unknown: Image not found

# We can't even get mirroring to-filesystem working ... other mirror modes are not even implemented right now, and this entire role will be "hidden" until we are able to verify it/get it working and re-tested.
