---
# Manage specific steps to configure JMS bundle servers
# ------------------------------------------------------------------------
- name: "Manage: JMS Configuration"
  when: mas_app_settings_server_bundles_size == 'jms'
  block:

  - name: Summary before loading Manage JMS config
    debug:
      msg:
      - "server_bundles_add_server_config_secret_name: {{ server_bundles_add_server_config_secret_name }}"
      - "server_bundle_jms_internal_endpoint: {{ server_bundle_jms_internal_endpoint }}"
      - "server_bundles_add_server_config_content: {{ server_bundles_add_server_config_content }}"
      - "server_bundles_jms_add_server_config_secret_name: {{ server_bundles_jms_add_server_config_secret_name }}"
      - "server_bundles_jms_add_server_config_content: {{ server_bundles_jms_add_server_config_content }}"

  - name: "Replace xml file with jms_internal_endpoint: {{ jms_internal_endpoint }}"
    replace: dest='{{ role_path }}/files/manage/manage-additional-server-config.xml.j2' regexp='server_bundle_jms_internal_endpoint' replace='{{ server_bundle_jms_internal_endpoint }}' backup=no

  - name: Create Manage app JMS additional server config secrets
    kubernetes.core.k8s:
      definition: "{{ lookup('template', 'templates/manage/manage-additional-server-config-secrets.yml.j2') }}"
