---
# If mas_app_settings_wml_version is informed, it takes precedence.
# When it is not informed we use cpd_product_version to obtain wml version to use
# When neither mas_app_settings_wml_version or cpd_product_version are informed, task fails

- name: Debug cpd_product_version and mas_app_settings_wml_version
  debug:
    msg:
      - "cpd_product_version .......................... {{ cpd_product_version }}"
      - "mas_app_settings_wml_version ................. {{ mas_app_settings_wml_version }}"

- name: Do not proceed if wml version cannot be obtained (either cpd_product_version or mas_app_settings_wml_version must be defined)
  assert:
    that: (cpd_product_version is defined and cpd_product_version != "" and cpd_product_version|length >= 3) or
          (mas_app_settings_wml_version is defined and mas_app_settings_wml_version != "")
    fail_msg: "Missing one or more required inputs for predict configuration"

- name: Obtain version of WML version to be used in predict activation
  when: mas_app_settings_wml_version is not defined or mas_app_settings_wml_version == ""
  set_fact:
    mas_app_settings_wml_version: "{{ cpd_wml_dictionary[cpd_product_version[0:3]] }}"

- name: Be sure mas_app_settings_wml_version is defined
  assert:
    that: mas_app_settings_wml_version is defined and mas_app_settings_wml_version != ""
    fail_msg: "mas_app_settings_wml_version cannot be obtained"

- name: Debug mas_app_settings_wml_version
  debug:
    msg: "mas_app_settings_wml_version ................. {{ mas_app_settings_wml_version }}"
