---
# Nvidia gpu namespace
gpu_namespace: "{{ lookup('env', 'GPU_NAMESPACE') | default('nvidia-gpu-operator', true) }}"

# Set channel for install and updates
gpu_channel: "{{ lookup('env', 'GPU_CHANNEL') | default('v1.11', true) }}"

# GPU driver version
# for ocp version 4.11
ocp_411_driver_version: 470.103.01
# for ocp version <= 4.10
ocp_410_driver_version: 450.80.02


# Variables for Node Feature Discovery Operator
# NFD namespace
nfd_namespace: "{{ lookup('env', 'NFD_NAMESPACE') | default('openshift-nfd', true) }}"

# channel for nfd install and updates
nfd_channel: "{{ lookup('env', 'NFD_CHANNEL') | default('stable', true) }}"
