---
cos_type: "{{ lookup('env', 'COS_TYPE') }}" # "ibm" or "ocs"
cos_action: "{{ lookup('env', 'COS_ACTION') | default('provision', True) }}" # "provision" or "deprovision"
cos_service: "cloud-object-storage"

# When these variables are defined we will create the ObjectStorageCfg resource,
# if either is missing then the configuration will not be generated
# ---------------------------------------------------------------------------------------------------------------------
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# OpenShift Container Storage Object Storage (ocs)
# ---------------------------------------------------------------------------------------------------------------------


# IBM Cloud Object Storage (ibm)
# ---------------------------------------------------------------------------------------------------------------------
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"
ibmcloud_resourcegroup: "{{ lookup('env', 'IBMCLOUD_RESOURCEGROUP') | default('Default', true) }}"

ibmcos_instance_name: "{{ lookup('env', 'COS_INSTANCE_NAME') }}"
ibmcos_location_info: "{{ lookup('env', 'COS_LOCATION') | default('global', True) }}"
ibmcos_plan_type: "{{ lookup('env', 'COS_PLAN') | default('standard', True) }}"
ibmcos_url: "{{ lookup('env', 'COS_REGION_LOCATION_URL') | default('https://s3.us.cloud-object-storage.appdomain.cloud', true) }}"
ibmcos_username: "ibmcloud-iam-apikey"
ibmcos_resource_key_iam_role: "{{ lookup('env', 'COS_RESOURCE_KEY_IAM_ROLE') | default('Manager', True) }}"
