---
# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - openshift_release_version is defined and openshift_release_version != ""
      - registry_public_host is defined and registry_public_host != ""
      - registry_public_port is defined and registry_public_port != ""
      - registry_username is defined and registry_username != ""
      - registry_password is defined and registry_password != ""
      - mirror_working_dir is defined and mirror_working_dir != ""
    fail_msg: "One or more required properties are missing"


# 2. Set up auth secret
# -----------------------------------------------------------------------------
- name: "Direct : Create working directory"
  file:
    path: "{{ ansible_env.HOME }}/.ibm-mas"
    state: directory

- name: "Direct : Create auth secret"
  ansible.builtin.template:
    src: templates/auth-secret.json.j2
    dest: "{{ auth_file }}"

- name: "Direct : Debug"
  debug:
    msg:
      - "Working Directory ...................... {{ mirror_working_dir }}"
      - "Mode ................................... {{ mirror_mode }}"
      - "Auth File .............................. {{ auth_file }}"


# 3. Perform Mirroring
# -----------------------------------------------------------------------------
- name: Mirror Release (from filesystem)
  shell: >
    oc image mirror \
      -a {{ auth_file }} \
      --from-dir={{ mirror_working_dir }} \
      'file://openshift/release:{{ openshift_release_version }}-x86_64*' \
      {{ registry_public_url }}/openshift/release \
      --insecure
  register: mirror_result

- name: "Debug Mirror"
  debug:
    msg: "{{ mirror_result.stdout_lines }}"
